FROM openjdk:11-jdk

COPY target/tipocambio-1.0.0.jar /app/tipocambio-1.0.0.jar

WORKDIR /app

# Comando para ejecutar la aplicación al iniciar el contenedor
CMD ["java", "-jar", "tipocambio-1.0.0.jar"]
